Snapshot from findutils-4.6.0.tar.gz

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,20 +1,19 @@
 AUTOMAKE_OPTIONS=gnits
 # readme-alpha
+AM_CFLAGS = $(WARN_CFLAGS)
 
-EXTRA_DIST = COPYING ChangeLog TODO config.h.in stamp-h.in \
-		THANKS import-gnulib.sh import-gnulib.config \
+EXTRA_DIST = COPYING ChangeLog ChangeLog-2013 TODO config.h.in stamp-h.in \
+		THANKS bootstrap \
 		tool-versions.txt README-hacking
 DISTCLEANFILES = tool-versions.txt
 
 
 # "tests" is the gnulib unit test dir.
-SUBDIRS = gnulib tests build-aux lib find xargs locate doc po m4 
+SUBDIRS = gl tests build-aux lib find xargs locate doc po m4
 
-ACLOCAL_AMFLAGS = -I gnulib/m4 -I m4
+ACLOCAL_AMFLAGS = -I gl/m4 -I m4
 
 TESTFILE_SUFFIXES = .exp .xo .xe .xi
-
-# CONFIG_CLEAN_FILES = gnulib/lib/regex.c
 
 tool-versions.txt: Makefile
 	( automake --version ; echo ; \
@@ -26,33 +25,32 @@ tool-versions.txt: Makefile
 	makeinfo --version ) > $@
 
 
-dist-hook: jy-regex-fix findutils-check-pofiles findutils-check-testfiles
+dist-hook: gen-ChangeLog findutils-check-pofiles findutils-check-testfiles
 
-
-## regex.c seems to get left out if I use automake-1.9 but not 
-## if I use automake-1.7.   Hence dist-hook has to be able to 
-## copy regex.c into the relevant (read-only) directory if it 
-## is not already there, but needs to avoid doing so if the 
-## file is already in place.   Ugh.  
-## 
-## This problem appears not to apply to Automake-1.10, but since
-## gnulib only requires Automake-1.9.6, we should support that.  
-## Therefore we probably can't remove this kludge yet.
-## 
-##                             -- James Youngman <jay@gnu.org>
-## 
-jy-regex-fix:
-	if test -f $(distdir)/gnulib/lib/regex.c ; then \
-		echo regex.c is already in place.  Great. ; \
-	else \
-		echo Making $(distdir)/gnulib/lib writable ... ; \
-		chmod +w $(distdir)/gnulib/lib ; \
-		echo Copying $(srcdir)/gnulib/lib/regex.c to $(distdir)/gnulib/lib ; \
-		cp $(srcdir)/gnulib/lib/regex.c $(distdir)/gnulib/lib/regex.c ; \
+# gen-Changelog must still work when $(top_srcdir)/.git does not exist
+# because "make distcheck" verifies that you can "make dist" from the
+# tarball generated by "make dist".  We still need that to work.
+.PHONY: gen-ChangeLog
+gen-ChangeLog:
+	$(AM_V_GEN)if test -d $(top_srcdir)/.git; then             \
+	  gen_start_date='2014-01-01' ;                            \
+	  log_fix="$(top_srcdir)/build-aux/git-log-fix" ;          \
+	  test -e "$$log_fix"                                      \
+	    && amend_git_log="--amend=$$log_fix"                   \
+	    || amend_git_log=;                                     \
+	  { $(top_srcdir)/build-aux/gitlog-to-changelog            \
+	      --srcdir=$(top_srcdir)                               \
+	      $$amend_git_log --since=$$gen_start_date             \
+	      && cat $(top_srcdir)/ChangeLog-2013 ;                \
+	    } > $(distdir)/cl-t                                    \
+	      && { rm -f $(distdir)/ChangeLog                      \
+		     && mv $(distdir)/cl-t $(distdir)/ChangeLog; } \
+	else                                                       \
+	  echo "WARNING: $@: cannot generate ChangeLog since" >&2 && \
+	  echo "$(top_srcdir) has no .git subdirectory" >&2 ;      \
 	fi
-#	ls -ld $(srcdir)/gnulib/lib/regex.c $(distdir)/gnulib/lib
 
-## Check that we actually shipped all the .po files.  If this rule fails, 
+## Check that we actually shipped all the .po files.  If this rule fails,
 ## check ALL_LINGUAS in configure.in against the po files in the source
 ## directory (their names, not their contents)
 findutils-check-pofiles:
@@ -61,7 +59,7 @@ findutils-check-pofiles:
 	@echo All .po files distributed OK.
 
 ## Check that we actually shipped all the test files that exist in the source.
-## runtest will run all the .exp files it finds, and so if we don't ship all 
+## runtest will run all the .exp files it finds, and so if we don't ship all
 ## of them, there will be some tests which people using the CVS code will be
 ## running, but people using the source distribution will not.
 findutils-check-testfiles:
@@ -71,7 +69,9 @@ findutils-check-testfiles:
 
 findutils-check-smells:
 	find  $(srcdir) \( -path $(srcdir)/autom4te.cache -o  \
-                           -path $(srcdir)/gnulib-git     -o  \
+                           -path $(srcdir)/gnulib     -o  \
+                           -path $(srcdir)/gl     -o  \
+                           -path $(srcdir)/tests     -o  \
                            -name .git             -o  \
                            \( -type d -name CVS \)  \
                        \) -prune -o                  \
@@ -79,3 +79,14 @@ findutils-check-smells:
 	\! \( -name '*~' -o -name '*.xo' -o -name '*.xi' \) \
 	-print0 | \
 	xargs -0 python $(AUXDIR)/src-sniff.py
+
+# Clean coverage files generated by running binaries built with gcc
+# -fprofile-arcs -ftest-coverage.  We touch subdirectories here
+# because the relecvant Makefile.am files (which we would otherwise
+# edit to add an $(RM) command in their own coverage-clean rule) are
+# generated by gnulib-tool and therefore we cannot add the rule to
+# those files.
+coverage-clean:
+	for dir in . gl/lib gl/lib/glthread gl/lib/uniwidth tests tests/uniwidth; do $(RM) $${dir}/*.gcno $${dir}/*.gcda $${dir}/*.gcov $${dir}/*.lcov; done
+
+clean-local: coverage-clean
